feed:
- uri: "at://did:plc:4acsffvbo4niovge362ptijz/xyz/abc1234"
  name: "Smoke Signal Support"
  description: "The Smoke Signal Support feed."
  allow: ["did:plc:cbkjy5n7bk3ax2wplmtjofq2", "did:plc:fjr24tyxkpi3xqenws7anfmj", "did:plc:4acsffvbo4niovge362ptijz"]
  deny: "at://did:plc:4acsffvbo4niovge362ptijz/app.bsky.feed.post/denied"
  matchers:
  - path: "$.did"
    value: "did:plc:tgudj2fjm77pzkuawquqhsxm"
    type: equal
  - path: "$.commit.record.text"
    values: ["smoke", "signal"]
    type: sequence
  - path: "$.commit.record.reply.parent.uri"
    value: "at://did:plc:tgudj2fjm77pzkuawquqhsxm/app.bsky.feed.post/"
    type: prefix
  - path: "$.commit.record.reply.root.uri"
    value: "at://did:plc:tgudj2fjm77pzkuawquqhsxm/app.bsky.feed.post/"
    type: prefix
