feeds:
- uri: "ATURI"
  name: "Engagement"
  description: "Posts that are talking about and engaging with my websites."
  matchers:
  # Matches text links
  - path: "$.commit.record.facets[*].features[?(@['$type'] == 'app.bsky.richtext.facet#link')].uri"
    value: "https://your.website/"
    type: prefix
  # Matches external embeded links
  - path: "$.commit.record.embed.external.uri"
    value: "https://your.website/"
    type: prefix
